/**
 * app/constants/locations.ts
 * List of countries and cities for location selection components.
 */

export const COUNTRIES = [
  "Indonesia",
  "Singapore",
  "Malaysia",
  "Thailand",
  "Philippines",
  "Vietnam",
  "Brunei",
  "Cambodia",
  "Laos",
  "Myanmar",
  "Timor-Leste",
  "Australia",
  "New Zealand",
  "Japan",
  "South Korea",
  "China",
  "India",
  "Saudi Arabia",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Germany",
  "France",
  "Netherlands",
  "Italy",
  "Canada",
  "Spain",
  "Switzerland",
  "Brazil",
  "Russia",
  "Egypt",
  "South Africa"
];

export const CITIES = [
  "Jakarta",
  "Bandung",
  "Surabaya",
  "Yogyakarta",
  "Medan",
  "Semarang",
  "Makassar",
  "Palembang",
  "Tangerang",
  "Bekasi",
  "Depok",
  "Bogor",
  "Malang",
  "Solo (Surakarta)",
  "Denpasar",
  "Balikpapan",
  "Samarinda",
  "Banjarmasin",
  "Pontianak",
  "Manado",
  "Palu",
  "Kendari",
  "Kupang",
  "Mataram",
  "Ambon",
  "Jayapura",
  "Banda Aceh",
  "Pekanbaru",
  "Padang",
  "Jambi",
  "Bandar Lampung",
  "Bengkulu",
  "Serang",
  "Batam",
  "Singapura",
  "Kuala Lumpur",
  "Tokyo",
  "Seoul",
  "London",
  "New York"
];
